import { Slider } from "@/interfaces/slider";

export const SLIDERS: Slider[] = [
  {
    id: "temperature",
    label: "Creativity",
    leftLabel: "Consistent",
    rightLabel: "Expressive",
    min: 0,
    max: 2,
    step: 0.1,
    defaultValue: 0.8,
    info: "The temperature of the speech. Higher values make the speech more creative and varied, while lower values make it more consistent and predictable.",
  },
  {
    id: "topP",
    label: "Voice Variety",
    leftLabel: "Stable",
    rightLabel: "Dynamic",
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: 0.95,
    info: "Nucleus sampling (top-p). Higher values consider more of the probability mass, making speech more varied and dynamic. Lower values focus on the most likely tokens, making speech more stable and predictable.",
  },
  {
    id: "topK",
    label: "Expression Range",
    leftLabel: "Subtle",
    rightLabel: "Dramatic",
    min: 1,
    max: 10000,
    step: 100,
    defaultValue: 1000,
    info: "Top-k sampling. Higher values allow more token choices, widening expression and drama. Lower values restrict choices, keeping speech more subtle and constrained.",
  },
  {
    id: "repetitionPenalty",
    label: "Natural Flow",
    leftLabel: "Rhythmic",
    rightLabel: "Varied",
    min: 1,
    max: 2,
    step: 0.1,
    defaultValue: 1.2,
    info: "Repetition penalty. Higher values discourage repeating phrases, producing more varied and natural flow. Lower values allow more repetition, producing a more rhythmic delivery.",
  },
];
